name: Build docker for master branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout Lunatic-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Lunatic-Model
          path: Lunatic-Model

      - name: Build Lunatic-Model with Maven
        working-directory: ./Lunatic-Model
        run: mvn clean generate-sources install -DskipTests

      - name: Checkout Pogues-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Pogues-Model
          path: Pogues-Model

      - name: Build with Maven Pogues-Model
        working-directory: ./Pogues-Model
        run: mvn clean generate-sources install -DskipTests

      - name: Checkout Pogues-Back-Office repo
        uses: actions/checkout@v2

      - name: Build with Maven Pogues-Back-Office
        run: mvn clean package -DskipTests -B -V --file pom.xml

      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: war
          path: target/
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: loichenninger/pogues-back-office
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
